spring.application.name=todowithmongo
spring.data.mongodb.uri=mongodb://localhost:27017/todo
spring.jackson.deserialization.fail-on-unknown-properties=true

# ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/todos} // while running with docker-compose
# mongodb://localhost:27017/todo   // while running locally with mongodb compass
# mongodb+srv://vedanshgupta292:hello234@cluster0.a7jfrg5.mongodb.net/todo  // while running with mongo atlas